sudo: required
services: 
  - docker

before_install:
  - docker build -f ./client/Dockerfile.dev -t amarmodi1784/react-test ./client

script:
  - docker run amarmodi1784/react-test npm test -- --coverage

after_success:
  - docker build -t amarmodi1784/multi-client ./client
  - docker build -t amarmodi1784/multi-server ./server
  - docker build -t amarmodi1784/multi-worker ./worker
  - docker build -t amarmodi1784/multi-nginx ./nginx
  # Login into the docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push to docker hub
  - docker push amarmodi1784/multi-client
  - docker push amarmodi1784/multi-server
  - docker push amarmodi1784/multi-worker
  - docker push amarmodi1784/multi-nginx